# Generated by Django 2.0.3 on 2018-03-22 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="date d'achat")),
                ('lieu', models.CharField(max_length=50, verbose_name="lieu d'achat")),
                ('type', models.CharField(choices=[('RA1', 'Rat - Rosé'), ('RA2', 'Rat - Blanchon'), ('RA3', 'Rat - Jeune'), ('RA4', 'Rat - Adulte'), ('SO1', 'Souris - Rosé'), ('SO2', 'Souris - Blanchon'), ('SO3', 'Souris - Sauteuse'), ('SO4', 'Souris - Adulte')], max_length=3, verbose_name='type')),
                ('quantite', models.IntegerField(verbose_name='quantité')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6, verbose_name="prix d'achat")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'achat',
                'verbose_name_plural': 'achats',
            },
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField(verbose_name="date d'entrée")),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='date de sortie')),
            ],
            options={
                'verbose_name': "emplacement d'un spécimen",
                'verbose_name_plural': 'emplacements des spécimens',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('type', models.IntegerField(choices=[(1, 'nettoyage du bac à eau'), (6, 'nettoyage des vitres'), (2, 'changement du substrat'), (3, 'retrait mues/excréments/salissures'), (4, 'désinfection'), (5, 'nettoyage complet')], verbose_name='Type')),
                ('remarque', models.CharField(blank=True, max_length=100, null=True, verbose_name='remarque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('type', models.IntegerField(choices=[(1, 'poids'), (2, 'taille')], verbose_name='type')),
                ('mesure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='mesure')),
            ],
            options={
                'verbose_name': 'mesure',
                'verbose_name_plural': 'mesures',
            },
        ),
        migrations.CreateModel(
            name='Mue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('remarque', models.CharField(blank=True, max_length=100, null=True, verbose_name='remarque')),
            ],
            options={
                'verbose_name': 'mue',
                'verbose_name_plural': 'mues',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=200, verbose_name='fichier')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('type', models.CharField(choices=[('RA1', 'Rat - Rosé'), ('RA2', 'Rat - Blanchon'), ('RA3', 'Rat - Jeune'), ('RA4', 'Rat - Adulte'), ('SO1', 'Souris - Rosé'), ('SO2', 'Souris - Blanchon'), ('SO3', 'Souris - Sauteuse'), ('SO4', 'Souris - Adulte')], max_length=3, verbose_name='proie')),
                ('quantite', models.IntegerField(verbose_name='quantité')),
                ('origine', models.CharField(max_length=50, verbose_name='origine')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='remarque')),
            ],
            options={
                'verbose_name': 'repas',
                'verbose_name_plural': 'repas',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('classe', models.CharField(max_length=50, verbose_name='classe')),
                ('espece', models.CharField(max_length=50, verbose_name='espèce')),
                ('sous_espece', models.CharField(max_length=50, verbose_name='sous-espèce')),
                ('phase', models.CharField(max_length=50, verbose_name='phase')),
                ('sexe', models.IntegerField(choices=[(1, 'mâle'), (2, 'femelle'), (3, 'indéterminé')], default=3, verbose_name='sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('date_entree', models.DateField(verbose_name="date d'entrée")),
                ('origine', models.CharField(blank=True, max_length=50, null=True, verbose_name='origine')),
                ('derniere_activite', models.DateTimeField(auto_now=True, verbose_name='dernière activité')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='prix')),
                ('alerte_repas', models.IntegerField(default=0, verbose_name='alerte repas après')),
                ('photos', models.ManyToManyField(to='book.Photo', verbose_name='photo')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'spécimen',
                'verbose_name_plural': 'spécimens',
            },
        ),
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('longueur', models.IntegerField(verbose_name='longueur')),
                ('largeur', models.IntegerField(verbose_name='largeur')),
                ('hauteur', models.IntegerField(verbose_name='hauteur')),
                ('substrat', models.CharField(blank=True, max_length=50, null=True, verbose_name='substrat')),
                ('temperature_point_chaud', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='température point chaud')),
                ('puissance_eclairage', models.IntegerField(blank=True, null=True, verbose_name="puissance d'éclairage")),
                ('puissance_chauffage', models.IntegerField(blank=True, null=True, verbose_name='puissance de chauffage')),
                ('duree_eclairage', models.IntegerField(blank=True, null=True, verbose_name="durée d'éclairage")),
                ('alerte_bac_eau', models.IntegerField(default=0, verbose_name='alerte nettoyage bac à eau après')),
                ('alerte_substrat', models.IntegerField(default=0, verbose_name='alerte changement de substrat après')),
                ('alerte_desinfection', models.IntegerField(default=0, verbose_name='alerte désincfection après')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'terrarium',
                'verbose_name_plural': 'terrariums',
            },
        ),
        migrations.AddField(
            model_name='repas',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to='book.Specimen', verbose_name='spécimen'),
        ),
        migrations.AddField(
            model_name='mue',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mues', to='book.Specimen', verbose_name='spécimen'),
        ),
        migrations.AddField(
            model_name='mesure',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='book.Specimen', verbose_name='spécimen'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='terrarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='book.Terrarium', verbose_name='terrarium'),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='book.Specimen', verbose_name='spécimen'),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='terrarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='book.Terrarium', verbose_name='terrarium'),
        ),
    ]
