# Generated by Django 2.0.3 on 2018-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='sous_espece',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sous-espèce'),
        ),
    ]
