# Generated by Django 2.0.3 on 2018-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180325_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='mesure',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='type',
        ),
        migrations.AddField(
            model_name='mesure',
            name='poids',
            field=models.IntegerField(blank=True, null=True, verbose_name='poids'),
        ),
        migrations.AddField(
            model_name='mesure',
            name='taille',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='taille'),
        ),
    ]
