# Generated by Django 2.0.3 on 2018-03-28 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_auto_20180326_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hivernation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='date de debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='specimen',
            index_together={('id', 'utilisateur')},
        ),
        migrations.AddField(
            model_name='hivernation',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hivernation', to='book.Specimen', verbose_name='spécimen'),
        ),
    ]
